name: MLflow CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Install MLflow
        run: pip install mlflow==2.19.0

      - name: Run MLflow Project
        run: mlflow run .

      - name: Build Docker Image from MLflow Model
        run: |
          # Ekstrak Run ID dari direktori mlruns
          # Di GitHub Actions, ini akan mengambil folder run id pertama yang dihasilkan
          RUN_ID=$(ls mlruns/0 | grep -E '^[0-9a-f]+$' | head -n 1)
          echo "Found RUN_ID: $RUN_ID"
          
          # Build docker image dengan model tersebut
          # Note: ${{ secrets.DOCKER_USERNAME }} akan diambil dari GitHub Secrets repo Anda
          mlflow models build-docker -m runs:/$RUN_ID/model -n ${{ secrets.DOCKER_USERNAME }}/hr-attrition-model:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          # Anda wajib mengatur secrets DOCKER_USERNAME dan DOCKER_PASSWORD
          # Di repository GitHub Anda -> Settings -> Secrets and variables -> Actions -> New repository secret
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image to Docker Hub
        run: |
          # Mengunggah image yang sudah di-build ke Docker Hub
          docker push ${{ secrets.DOCKER_USERNAME }}/hr-attrition-model:latest
